### ISSUE TITLE
nginx-swarm 503

### ISSUE THREAD

**Issue by krishamoud** [ehazlett/interlock#105]
Hi!  First thank you and all contributors for this image.

Second, I have created a swarm locally using virtualbox that has 3 nodes and I used the `docker-compose.yml` file in the /docs/examples folder.

This is my `config.toml`
```
listenAddr = ":8080"
dockerURL = "tcp://192.168.99.168:4000"  #$(docker-machine ip manager):4000
TLSCACert = "/etc/docker/ca.pem"
TLSCert = "/etc/docker/server.pem"
TLSKey = "/etc/docker/server-key.pem"
AllowInsecure = false
EnableMetrics = true

[[extensions]]
name = "nginx"
configPath = "/etc/conf/nginx.conf"
pidPath = "/etc/conf/nginx.pid"
maxConn = 1024
port = 80
```

This is my `docker-compose.yml` file which is the same as the one in the examples folder with the exception of the added tls mount.
```
interlock:
    image: ehazlett/interlock:1.0
    command: run
    ports:
        - 8080
    volumes:
        - ./config.toml:/bin/config.toml
        - nginx:/etc/conf
        - /var/run/docker.sock:/var/run/docker.sock
        - ${DOCKER_CERT_PATH}:/etc/docker/

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/conf/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock
    volumes:
        - nginx:/etc/conf

app:
    image: ehazlett/docker-demo:latest
    ports:
        - 8080
    labels:
        - "interlock.hostname=test"
        - "interlock.domain=local"

```

When I run `docker-compose up -d` everything starts fine and after checking the logs I can see that interlock is updating the configuration because this is the output.

```
time="2016-03-21T22:23:58Z" level=info msg="interlock 1.0.0 (49863fc)"
time="2016-03-21T22:23:58Z" level=info msg="test.local: upstream=192.168.99.172:32768" ext=nginx
time="2016-03-21T22:23:58Z" level=info msg="configuration updated" ext=nginx
```

Then if I run `docker-compose scale app=3` I can see that they are also being added because this is the combined output.

```
time="2016-03-21T22:23:58Z" level=info msg="interlock 1.0.0 (49863fc)"
time="2016-03-21T22:23:58Z" level=info msg="test.local: upstream=192.168.99.172:32768" ext=nginx
time="2016-03-21T22:23:58Z" level=info msg="configuration updated" ext=nginx
time="2016-03-21T22:34:37Z" level=info msg="test.local: upstream=192.168.99.170:32768" ext=nginx
time="2016-03-21T22:34:37Z" level=info msg="test.local: upstream=192.168.99.172:32769" ext=nginx
time="2016-03-21T22:34:37Z" level=info msg="test.local: upstream=192.168.99.172:32768" ext=nginx
time="2016-03-21T22:34:37Z" level=info msg="configuration updated" ext=nginx
time="2016-03-21T22:34:37Z" level=info msg="restarted proxy container: id=9fc1f9e116e2 name=/node1/nginxswarm_nginx_1" ext=nginx
```

When I run `docker exec -t fa cat /etc/conf/nginx.conf` I get this

```
# managed by interlock
user  www-data;
worker_processes  2;
worker_rlimit_nofile 65535;

error_log  /var/log/error.log warn;
pid        /etc/conf/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    server_names_hash_bucket_size 128;
    client_max_body_size 2048M;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    # If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
    # scheme used to connect to this server
    map $http_x_forwarded_proto $proxy_x_forwarded_proto {
      default $http_x_forwarded_proto;
      ''      $scheme;
    }

    #gzip  on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    proxy_set_header        X-Real-IP         $remote_addr;
    proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $proxy_x_forwarded_proto;
    proxy_set_header        Host              $http_host;
    send_timeout 600;

    # ssl
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    # default host return 503
    server {
            listen 80;
            server_name _;

            location / {
                return 503;
            }

            location /nginx_status {
                stub_status on;
                access_log off;
            }
    }


    upstream test.local {
        zone test.local_backend 64k;

        server 192.168.99.170:32768;
        server 192.168.99.172:32769;
        server 192.168.99.172:32768;

    }
    server {
        listen 80;

        server_name test.local;

        location / {
            proxy_pass http://test.local;
        }



    }



    include /etc/conf/conf.d/*.conf;
}
```

I see that my hosts have been added but when I visit `192.168.99.171:80->80/tcp` I get the NGINX 503  Service Temporarily Unavailable screen.

I feel like I'm missing something very small but I don't know what it is.  

Thanks in advance!

Kris
