### ISSUE TITLE
Global SSL configuration for nginx

### ISSUE THREAD

**Issue by jleuleu** [ehazlett/interlock#109]
Is there a way to set a global configuration for SSL such that all containers are only accessible via HTTPS with the same certificate?

So far, I've only been able to set the configuration individually for each containers (see docker-compose below).
I would like to deploy several containers, one per subdomains (e.g web1.example.com, web2.example.com) and all of them should be accessible via HTTPS with the same certificate (*.example.com)

```
interlock:
    image: ehazlett/interlock:1.0.1
    command: -D run
    tty: true
    ports:
        - 8080
    environment: 
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${SWARM_HOST}"
            TLSCACert = "/var/lib/boot2docker/ca.pem"
            TLSCert = "/var/lib/boot2docker/server.pem"
            TLSKey = "/var/lib/boot2docker/server-key.pem"
            
            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/conf/nginx.conf"
            PidPath = "/etc/conf/nginx.pid"
            MaxConn = 1024
            Port = 80
            SSLCertPath = "/certs"
            SSLPort = 443
    volumes:
        - nginx:/etc/conf
        - /var/lib/boot2docker:/var/lib/boot2docker:ro
        - /var/tmp/config.toml:/bin/config.toml
        - ~/cert2016:/certs

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/conf/nginx.conf
    ports:
        - 80:80
        - 443:443
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock
    volumes:
        - nginx:/etc/conf
        - ~/cert2016:/certs

web1:
    image: dockercloud/hello-world:latest
    ports:
        - 80
    labels:
        - "interlock.hostname=web1"
        - "interlock.domain=example.com"
        - "interlock.ssl=true"
        - "interlock.ssl_only=true"
        - "interlock.ssl_cert=example.com.crt"
        - "interlock.ssl_cert_key=example.com.key"
web2:
    image: dockercloud/hello-world:latest
    ports:
        - 80
    labels:
        - "interlock.hostname=web2"
        - "interlock.domain=example.com"
        - "interlock.ssl=true"
        - "interlock.ssl_only=true"
        - "interlock.ssl_cert=example.com.crt"
        - "interlock.ssl_cert_key=example.com.key"
```
