### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by princemaple** [ehazlett/interlock#119]
while it works perfectly on local boot2docker machine created by docker machine

it gives me this

```
 ❯ docker-compose up interlock
Creating network "app_default" with the default driver
Creating volume "app_pg_data" with local driver
Creating app_interlock_1
Attaching to app_interlock_1
interlock_1 | time="2016-04-13T07:27:25Z" level=info msg="interlock 1.1.0 (8a68c99)"
interlock_1 | time="2016-04-13T07:27:25Z" level=debug msg="loading config from: /bin/config.toml"
interlock_1 | time="2016-04-13T07:27:25Z" level=debug msg="docker client: url=unix:///var/run/docker.sock"
interlock_1 | time="2016-04-13T07:27:25Z" level=debug msg="loading extension: name=haproxy"
interlock_1 | panic: runtime error: index out of range
interlock_1 |
interlock_1 | goroutine 1 [running]:
interlock_1 | panic(0xba2240, 0xc820010010)
interlock_1 |   /usr/local/go/src/runtime/panic.go:464 +0x3e6
interlock_1 | github.com/ehazlett/interlock/ext/lb.getNodeID(0x0, 0x0, 0x0, 0x0)
interlock_1 |   /go/src/github.com/ehazlett/interlock/ext/lb/utils.go:35 +0x52d
interlock_1 | github.com/ehazlett/interlock/ext/lb.NewLoadBalancer(0xc820170480, 0xc82016d920, 0xcd5798, 0x0, 0x0)
interlock_1 |   /go/src/github.com/ehazlett/interlock/ext/lb/lb.go:93 +0x1d0
interlock_1 | github.com/ehazlett/interlock/server.(*Server).loadExtensions(0xc82016d800, 0xc82016d920)
interlock_1 |   /go/src/github.com/ehazlett/interlock/server/server.go:171 +0x236
interlock_1 | github.com/ehazlett/interlock/server.NewServer(0xc820112b00, 0x16d, 0x0, 0x0)
interlock_1 |   /go/src/github.com/ehazlett/interlock/server/server.go:112 +0x280
interlock_1 | main.runAction(0xc820137040)
interlock_1 |   /go/src/github.com/ehazlett/interlock/cmd/interlock/run.go:186 +0xc8f
interlock_1 | github.com/ehazlett/interlock/vendor/github.com/codegangsta/cli.Command.Run(0xcd7fd0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcf0ae0, 0xd, 0x0, ...)
interlock_1 |   /go/src/github.com/ehazlett/interlock/vendor/github.com/codegangsta/cli/command.go:174 +0x1399
interlock_1 | github.com/ehazlett/interlock/vendor/github.com/codegangsta/cli.(*App).Run(0xc820136dc0, 0xc82000a0a0, 0x5, 0x5, 0x0, 0x0)
interlock_1 |   /go/src/github.com/ehazlett/interlock/vendor/github.com/codegangsta/cli/app.go:187 +0x112b
interlock_1 | main.main()
interlock_1 |   /go/src/github.com/ehazlett/interlock/cmd/interlock/main.go:36 +0x3db
app_interlock_1 exited with code 2
```

on 

```
 ❯ uname -rsm
Linux 4.4.4-std-3 x86_64
```

Would you happen to know why?

I tried pulling this repo and running the examples, same error.

**EDIT:** changed `dc` to `docker-compose` to reflect that it's just an alias

**Comment by princemaple** [comment]
FYI this is on a VPS on scaleway.com

**Comment by ehazlett** [comment]
Ya Interlock needs to run in a container. That's the getNodeID error
although it should report a better error. I will take a look.

**Comment by princemaple** [comment]
That's weird, it **is** run in a container. Hmm. Is there any other information I can provide you with?

**Comment by princemaple** [comment]
And thank you so much for the super timely response.

**Comment by ehazlett** [comment]
Oh odd. Can you give me some more info about the host?  Docker version, OS
etc.

**Comment by ehazlett** [comment]
Yw :). It's late for me so I will check this out more in the morning. :).
Host info will help. I'll try to reproduce. Thx!

**Comment by princemaple** [comment]
```
 ⚡ root@scw-10c99b  /v/app 
 ❯ docker-compose version
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

 ⚡ root@scw-10c99b  /v/app 
 ❯ uname -a
Linux scw-10c99b 4.4.4-std-3 #1 SMP Tue Mar 8 17:31:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

my compose file

```yml
version: '2'
services:
  interlock:
    image: ehazlett/interlock:1.1.0
    command: run -c /bin/config.toml
    ports:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/bin/config.toml
  lb:
    image: haproxy:1.6.4
    labels:
      - "interlock.ext.name=haproxy"
    ports:
      - 80:80
    depends_on:
      - interlock
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - MIX_ENV=dev
    image: schedule
    hostname: docker.dev
    ports:
      - 4000
    environment:
      JWT_SECRET_KEY: |-
        abc123abc123abc123abc123abc123abc123abc123abc123abc123abc
        123abc123abc123abc123abc123abc123abc123abc123abc123abc123
    volumes:
      - ./web:/var/app/web
      - ./config:/var/app/config
      - ./priv:/var/app/priv
      - ./lib:/var/app/lib
      - ./test:/var/app/test
      - ./mix.exs:/var/app/mix.exs
      - ./mix.lock:/var/app/mix.lock
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
  registrator:
    image: gliderlabs/registrator:master
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal -resync 600 consul://consul:8500
  consul:
    image: gliderlabs/consul-server:0.6
    command: "-bootstrap"
  assets:
    build:
      context: .
      dockerfile: Dockerfile.assets
    image: schedule_assets
    volumes:
      - ./web/static:/var/build/web/static
      - ./priv/static:/var/build/priv/static
      - ./.eslintrc:/var/build/.eslintrc
      - ./webpack.config.js:/var/build/webpack.config.js
volumes:
  pg_data:
    driver: local
```
