### ISSUE TITLE
nginx customized template ignored

### ISSUE THREAD

**Issue by demaniak** [ehazlett/interlock#148]
Might relate to #114 , #147 

Basically, working from the nginx example, I am unable to get interlock to use a custom template for nginx configuration generation.

Example compose file slightly modified as follows:

```
interlock:
    image: ehazlett/interlock:1.1.0
    command: run -c /etc/interlock/config.toml
    ports:
        - 8080
    volumes:
        - ./config.toml:/etc/interlock/config.toml
        - ./nginx.conf.template:/etc/interlock/nginx.conf.template
        - /var/run/docker.sock:/var/run/docker.sock

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock

app:
    image: ehazlett/docker-demo:latest
    ports:
        - 8080
    labels:
        - "interlock.hostname=test"
        - "interlock.domain=ag"
```

The template found in the running `interlock` container is correct, but the config generated for nginx on a docker event completely ommits any changes applied to the template. 

It LOOKS almost like interlock can't find the template, and just default everything (apart from what it could find `config.toml` - that it seems to find and honour).
