### ISSUE TITLE
Nginx config not reloaded

### ISSUE THREAD

**Issue by amsdard** [ehazlett/interlock#165]
Hi,

don't know what I'm doing wrong but nginx config is not always being reloaded. I'm testing it on a simple swarm setup (master + 1 node). When I run app container on the same node as interlock and nginx everything is fine, but if I run it on other node, nginx is not reloaded, there is no event logged by interlock.

Weird thing is that if I first start app container  and then start interlock with nginx, app container is detected no matter on which node it is running. But if I stop app container, nginx is not reloaded. 

I've been trying couple combinations, using interlock.port, interlock.network but no luck.

My stack:
docker-compose: 1.7.1
docker sever version: 1.11.1
swarm/1.2.2

```yaml
version: "2"

services:
  interlock:
    image: ehazlett/interlock:1.1.3
    command: -D run -c /etc/interlock/config.toml
    container_name: interlock
    ports:
      - 8080
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "tcp://172.28.128.200:3376"
            TLSCACert = "/etc/docker/ca.pem"
            TLSCert = "/etc/docker/server.pem"
            TLSKey = "/etc/docker/server-key.pem"

            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/var/run/nginx.pid"
            TemplatePath = ""
            MaxConn = 1024
            Port = 80
            NginxPlusEnabled = false
    volumes:
      - /etc/docker:/etc/docker
      - nginx:/etc/nginx

  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
      - "80:80"
    labels:
      - "interlock.ext.name=nginx"
    links:
      - interlock:interlock
    volumes:
      - nginx:/etc/nginx

volumes:
  nginx:
    driver: local
```

I run web app like this:
```bash
docker run -it --rm -p 80 -l interlock.hostname=test -l interlock.domain=local tutum/hello-world
```

Any idea what it might be or what I'm doing wrong here?
