### ISSUE TITLE
Real IP not forwarded to app container

### ISSUE THREAD

**Issue by dymat** [ehazlett/interlock#174]
Hi there!

I use interlock to manage serveral web apps on the same host. 

For one app I need the real ip address of the visitor to be passed to the app container. But neither the reverse nginx nor the app container see the real ip. On both I get 172.18.0.1.

As I understand the nginx.conf.template the real ip should be forwarded...

Could it be a bug or is it just bad configured on my side?

Thanks in advance for any hint,
~D

Here's my configuration:

**docker-compose.yml**
```
version: "2"

services:
    interlock:
        image: ehazlett/interlock:1.2.0
        command: run -c /etc/interlock/config.toml
        ports:
            - 8080
        volumes:
            - ./config.toml:/etc/interlock/config.toml
            - ./nginx.conf.template:/etc/interlock/nginx.conf.template
            - /var/run/docker.sock:/var/run/docker.sock
    
    nginx:
        image: nginx:latest
        entrypoint: nginx
        command: -g "daemon off;" -c /etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        labels:
            - "interlock.ext.name=nginx"
        links:
            - interlock:interlock
        depends_on:
            - interlock
        
        volumes:
            - /etc/letsencrypt/live/:/etc/letsencrypt/live/
            - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/
        restart: always
        
    mysite:
        build: ./mysite/
        ports:
            - 80
        volumes:
            - ./mysite/html:/var/www/html
            - ./mysite/logs:/var/log/nginx
        labels:
            - "interlock.hostname=mysite"
            - "interlock.domain=de"
            - "interlock.alias_domain.1=www.mysite.de"
            - "interlock.alias_domain.2=www.mysite.com"
            - "interlock.alias_domain.3=mysite.com"
            - "interlock.ssl=true"
            - "interlock.ssl_cert=/etc/letsencrypt/live/mysite/fullchain.pem"
            - "interlock.ssl_cert_key=/etc/letsencrypt/live/mysite/privkey.pem"
        restart: always
        links:
            - db
    db:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        volumes:
            - ./mysite/mysql:/var/lib/mysql
            - ./mysite/dbinit:/docker-entrypoint-initdb.d/
```

**config.toml**

```
ListenAddr = ":8080"
DockerURL = "unix:///var/run/docker.sock"

[[Extensions]]
Name = "nginx"
ConfigPath = "/etc/nginx/nginx.conf"
PidPath = "/var/run/nginx.pid"
TemplatePath = "/etc/interlock/nginx.conf.template"
BackendOverrideAddress = "172.17.0.1"
MaxConn = 1024
Port = 80
SSLPort = 443
NginxPlusEnabled = false
```

**nginx.conf.template**
[https://github.com/ehazlett/interlock/blob/master/docs/examples/nginx/nginx.conf.template.example](https://github.com/ehazlett/interlock/blob/master/docs/examples/nginx/nginx.conf.template.example)
