### ISSUE TITLE
doesn't recognize containers in the swarm 

### ISSUE THREAD

**Issue by troubleshooter713** [ehazlett/interlock#192]
First thank you for all your work!

I have been struggling to get this working for a while now, I've tried to follow the examples:
 at scale guide
nginx-swarm
nginx-swarm-machine
haproxy

with no success on any. I have consul, interlock, nginx and the app running, but cannot get the loadbalancer to see the local apps or apps in the swarm. I all I get is 503 and 502 errors, but I can get to the containers directly (via port), but never able to connect though the lb.

Docker version 1.11.2, build b9f10c9
swarm: latest
interlock:1.2.0 (running on the swarm manager)

my config.toml
 ```
ListenAddr = ":8080"
 DockerURL = "tcp://10.255.92.44:2375"
 
 [[Extensions]]
 Name = "nginx"
 ConfigPath = "/etc/nginx/nginx.conf"
 PidPath = "/var/run/nginx.pid"
 TemplatePath = "/etc/interlock/nginx.conf.template"
 #BackendOverrideAddress = "172.17.0.1"
 MaxConn = 1024
 Port = 80
 NginxPlusEnabled = false
```

docker-compose.yml
```
interlock:
    image: ehazlett/interlock:master
    command: run -c /etc/interlock/config.toml
    tty: true
    ports:
        - 8080
    volumes:
        - ./config.toml:/etc/interlock/config.toml
        - ./nginx.conf.template:/etc/interlock/nginx.conf.template
        - nginx:/etc/nginx

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock
    volumes:
        - nginx:/etc/nginx

app:
    image: ehazlett/docker-demo:latest
    hostname: local.foo
    ports:
        - 8080
    labels:
        - "interlock.hostname=local"
        - "interlock.domain=foo"
```

I'm not exactly sure what I'm missing, but here is the output of the interlock container:
```
INFO[0000] interlock 1.2.0-master (2fd9af6)             
DEBU[0000] loading config from environment              
DEBU[0000] docker client: url=tcp://10.255.92.44:2375   
DEBU[0000] loading extension: name=nginx                
DEBU[0000] using internal configuration template         ext=lb
INFO[0000] interlock node: id=3887443f2756fc19db351b515b1b2f5a491634ad9e119704ecaea89912200795  ext=lb
DEBU[0000] starting event handling                      
INFO[0000] using event stream                           
DEBU[0000] event received: status=interlock-start id=0 type= action= 
DEBU[0000] notifying extension: lb                      
DEBU[0000] triggering reload                             ext=lb
DEBU[0004] reaping key: reload                          
DEBU[0004] triggering reload from cache                  ext=lb
DEBU[0004] checking to reload                            ext=lb
DEBU[0004] updating load balancers                       ext=lb
DEBU[0004] generating proxy config                       ext=lb
DEBU[0004] proxy config path: /etc/nginx/nginx.conf      ext=lb
DEBU[0004] detected proxy container: id=cf5544f25d6dbb7f6ebb4624a6e19f56fd67523b14fbda74d9570fe3f632e75c backend=nginx  ext=lb
```
in the logs interlock sees the local containers, but not the containers on the swarm, no matter how many or few I generate is only sees the locals, but the load balancing still doesn't happen.
```
DEBU[0115] triggering reload                             ext=lb
DEBU[0118] reaping key: reload                          
DEBU[0118] triggering reload from cache                  ext=lb
DEBU[0118] checking to reload                            ext=lb
DEBU[0118] updating load balancers                       ext=lb
DEBU[0118] generating proxy config                       ext=lb
DEBU[0118] websocket endpoints: []                       ext=nginx
DEBU[0118] alias domains: []                             ext=nginx
INFO[0118] local.foo: upstream=0.0.0.0:32861             ext=nginx
DEBU[0118] websocket endpoints: []                       ext=nginx
DEBU[0118] alias domains: []                             ext=nginx
INFO[0118] local.foo: upstream=0.0.0.0:32860             ext=nginx
DEBU[0118] websocket endpoints: []                       ext=nginx
DEBU[0118] alias domains: []                             ext=nginx
INFO[0118] local.foo: upstream=0.0.0.0:32859             ext=nginx
DEBU[0118] websocket endpoints: []                       ext=nginx
DEBU[0118] alias domains: []                             ext=nginx
INFO[0118] local.foo: upstream=0.0.0.0:32858             ext=nginx
```
if anyone can point me in the right direction, it would be greatly appreciated.
