### ISSUE TITLE
nginx crashes if two containers with the same hostname

### ISSUE THREAD

**Issue by adamjimenez** [ehazlett/interlock#73]
```
duplicate upstream "xxx" in /etc/nginx/nginx.conf:425  
```

perhaps this could be handled more gracefully?

**Comment by ehazlett** [comment]
Thanks for the report.  I will take a look.

**Comment by rofr** [comment]
I can start multiple tutum/hello-world containers with the same hostname and they all receive trafik from the nginx proxy. Is this issue resolved?

**Comment by ehazlett** [comment]
@rofr thx for the update.  i've added this to the 1.2. milestone to confirm it's working.  thx!

**Comment by krishamoud** [comment]
I've found this bug myself with `interlock:master`.  To reproduce this start 2 containers with the same hostname.  This will work as expected but then if you stop the nginx container and try to start it again it will crash with the error printed above.

**Comment by ehazlett** [comment]
In testing master I cannot reproduce.  I am using the sample compose config in `docs/examples`.  I set the `hostname=foo` and scaled to 10 containers.  I then restarted nginx and everything worked.  I'm not seeing this.  @krishamoud / @adamjimenez  Do you have an example compose or setup I can use to re-create?

**Comment by krishamoud** [comment]
Hey sorry I'm getting back to this so late.  I'm not sure if this issue is the same as the one this thread started on but I have been able to reproduce it.  It appears to be a websocket endpoint issue.

```
interlock:
    image: ehazlett/interlock:master
    command: -D run
    tty: true
    ports:
        - 8080
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${SWARM_HOST}"
            TLSCACert = "/var/lib/boot2docker/ca.pem"
            TLSCert = "/var/lib/boot2docker/server.pem"
            TLSKey = "/var/lib/boot2docker/server-key.pem"
            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/etc/nginx/nginx.pid"
            MaxConn = 1024
            Port = 80
    volumes:
        - /var/lib/boot2docker:/var/lib/boot2docker:ro

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
app:
    image: ehazlett/docker-demo:latest
    hostname: test.local
    ports:
        - 8080
    labels:
        - "interlock.hostname=test"
        - "interlock.domain=local"
        - "interlock.websocket_endpoint=/websocket"
```

If you run the above it will work as expected.  If you scale it, it will also work as expected but if you restart nginx it will crash with this error 
```
2016/05/18 21:16:04 [emerg] 1#1: duplicate location "/nginx_status" in /etc/nginx/nginx.conf:116
nginx: [emerg] duplicate location "/nginx_status" in /etc/nginx/nginx.conf:116
```

However if you run this instead:
```
...
app:
    image: ehazlett/docker-demo:latest
    hostname: test.local
    ports:
        - 8080
    labels:
        - "interlock.hostname=test"
        - "interlock.domain=local"
        # - "interlock.websocket_endpoint=/websocket"
```
you can start/stop/scale as much as you'd like.

When the app is scaled with websockets the nginx.conf will looks something like this

```
...
upstream test.local {
        zone test.local_backend 64k;

        server 192.168.99.103:32777;
        server 192.168.99.104:32775;
        server 192.168.99.103:32776;

    }
    server {
        listen 80;

        server_name test.local;

        location / {
            proxy_pass http://test.local;
        }


        location /websocket {
            proxy_pass http://test.local;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location /nginx_status {
            stub_status on;
            access_log off;
        }


        location /websocket {
            proxy_pass http://test.local;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location /nginx_status {
            stub_status on;
            access_log off;
        }


        location /websocket {
            proxy_pass http://test.local;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location /nginx_status {
            stub_status on;
            access_log off;
        }



    }
```

I suspect that the issue is being caused by creating one websocket endpoint per scaled container.
