### ISSUE TITLE
v1.0.0 will not work with UCP/Swarm and overlay network

### ISSUE THREAD

**Issue by robbydooo** [ehazlett/interlock#82]
Hi there,

I have spent the last few days trying to get interlock v1.0.0 to work on our UCP/Swarm cluster but with no luck.

Using the overlay network seems to break the generation of the configuration files.
Example Compose file:

```
version: "2"

services:
  
  webapp:
    image: ‘blah:latest’
    environment:
      - "constraint:node==production-frontend*"
    expose:
      - '80'
    labels:
      - "interlock.hostname=www”
      - "interlock.domain=blah.com”
    depends_on:
      - interlock

  interlock:
      image: blah/interlock:1.0.0
      command: run -c /bin/config.toml
      ports:
          - 8080
      volumes:
          - haproxy:/etc
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/discovery_certs:/var/lib/docker/discovery_certs
      environment:
        - "constraint:node==production-frontend-1"

  haproxy:
      image: haproxy:latest
      ports:
          - 80:80
      labels:
          - "interlock.ext.name=haproxy"
      volumes:
          - haproxy:/usr/local/etc/haproxy
      environment:
        - "constraint:node==production-frontend-1"
      depends_on:
        - interlock


networks:
  default:
    external:
      name: overlay_network

volumes:
  haproxy:

```

Toml config file:

```

listenAddr = ":8080"
dockerURL = "tcp://<UCP/SWARM IP>:2376"
TLSCACert = "/var/lib/docker/discovery_certs/ca.pem"
TLSCert = "/var/lib/docker/discovery_certs/cert.pem"
TLSKey = "/var/lib/docker/discovery_certs/key.pem"
AllowInsecure = false
EnableMetrics = true

[[extensions]]
name = "haproxy"
configPath = "/etc/haproxy.cfg"
pidPath = "/etc/haproxy.pid"
maxConn = 1024
port = 80
adminUser = "admin"
adminPass = "interlock"

```

This generates the following haproxy.conf

```

backend www_blah_com
    http-response add-header X-Request-Start %Ts.%ms
    balance roundrobin



    server blah_webapp_4 : check inter 5000
    server  blah_webapp_3 : check inter 5000
    server  blah_webapp_2 : check inter 5000
    server  blah_webapp_1 : check inter 5000

```

I believe it should be something like:

This generates the following haproxy.conf

```

backend www_blah_com
    http-response add-header X-Request-Start %Ts.%ms
    balance roundrobin



    server blah_webapp_4  1.2.3.4:80 check inter 5000
    server  blah_webapp_3 2.3.4.5:80 check inter 5000

  etc etc....

```

As a result the haproxy shows all nodes being down  "Layer 4 connection problem".

If I manually run curl against the blah_webapp_4 then it returns the webpage just fine so there has to be an issue with configuration somewhere.

**Comment by ehazlett** [comment]
It looks like you are binding the Docker socket into the Interlock container.  How are you mounting the config.toml?  It looks like you are specifying a default which would use the Docker socket instead of Swarm which would cause the IP to be blank.

I recommend this reference architecture for using Interlock on UCP https://blog.docker.com/2016/03/configuring-load-balancing-service-discovery-docker-universal-control-plane/.

Here is an example Compose file to start Interlock on UCP: https://github.com/nicolaka/interlock-lbs/blob/master/interlock-haproxy/docker-compose.yml

**Comment by robbydooo** [comment]
Thanks for the links,

unfortunately that hasnt fixed the problems.

The config.toml was being loaded in correctly as I was building a custom image including our modified version. To make this easier though I have used the example version you sent using etcd for configuring and still getting the same issue.

It picks up the web app containers are coming up but doesnt seem to find the IP and socket information:

```

nterlock_1 | time="2016-03-04T12:52:36Z" level=info msg="interlock 1.0.0 (49863fc)"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="using kv: addr=etcd://10.99.8.5:12379"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="Trusting certs with subjects: [0\x1e1\x1c0\x1a\x06\x03U\x04\x03\x13\x13UCP Cluster Root CA]"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="configuring TLS for KV"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="using tls for communication with docker"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="docker client: url=tcp://10.99.8.5:2376"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="loading extension: name=nginx configpath=/etc/conf/nginx.conf"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="starting event handling"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="checking to reload"
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg=reloading
interlock_1 | time="2016-03-04T12:52:36Z" level=debug msg="updating load balancers"
interlock_1 | time="2016-03-04T12:52:37Z" level=info msg="configuration updated" ext=nginx
interlock_1 | time="2016-03-04T12:52:37Z" level=debug msg="reload duration: 683.89ms"
interlock_1 | time="2016-03-04T12:52:37Z" level=debug msg="event received: type=create id=e19d0db621d3ac0aebb3dace996b25753c2ca52e55acb30c42d8674e71145d67"
interlock_1 | time="2016-03-04T12:52:37Z" level=debug msg="event received: type=attach id=e19d0db621d3ac0aebb3dace996b25753c2ca52e55acb30c42d8674e71145d67"
....................
interlock_1 | time="2016-03-04T12:54:54Z" level=debug msg=reloading
interlock_1 | time="2016-03-04T12:54:54Z" level=debug msg="updating load balancers"
interlock_1 | time="2016-03-04T12:54:54Z" level=debug msg="websocket endpoints: []" ext=nginx
interlock_1 | time="2016-03-04T12:54:54Z" level=debug msg="alias domains: []" ext=nginx
interlock_1 | time="2016-03-04T12:54:54Z" level=info msg="www.blah.com: upstream=:" ext=nginx

```

docker-compose:

````

version : "2"

services:

 interlock:
      image: ehazlett/interlock:1.0.0
      command: -D run --discovery etcd://10.99.8.5:12379 --discovery-tls-ca-cert /var/lib/docker/discovery_certs/ca.pem --discovery-tls-cert /var/lib/docker/discovery_certs/cert.pem --discovery-tls-key /var/lib/docker/discovery_certs/key.pem
      volumes:
        - /var/lib/docker/discovery_certs:/var/lib/docker/discovery_certs/
        - nginx:/etc/conf
      environment:
        - "constraint:node==production-frontend-1"
 nginx:
      image: nginx
      command: nginx -g "daemon off;" -c /etc/conf/nginx.conf
      ports:
          - 80:80
          - 443:443
      labels:
          - "interlock.ext.name=nginx"
      volumes:
          - nginx:/etc/conf
      depends_on:
          - interlock
      environment:
          - "constraint:node==production-frontend-1"

volumes:
  nginx:

networks:
  default:
    external:
      name: production_hwd

````

Toml file in etcd:

````

curl --cert /var/lib/docker/discovery_certs/cert.pem --key /var/lib/docker/discovery_certs/key.pem --cacert /var/lib/docker/discovery_certs/ca.pem -L https://10.99.8.5:12379/v2/keys/interlock/v1/config -XPUT -d value='
listenAddr = ":8080"
dockerURL = "tcp://10.99.8.5:2376"
TLSCACert = "/var/lib/docker/discovery_certs/ca.pem"
TLSCert = "/var/lib/docker/discovery_certs/cert.pem"
TLSKey = "/var/lib/docker/discovery_certs/key.pem"
AllowInsecure = false
EnableMetrics = true

[[Extensions]]
    Name = "nginx"
    ConfigPath = "/etc/conf/nginx.conf"
    PidPath = "/etc/conf/nginx.pid"
    BackendOverrideAddress = ""
    ConnectTimeout = 5000
    ServerTimeout = 10000
    ClientTimeout = 10000
    MaxConn = 1024
    Port = 80
    SyslogAddr = ""
    NginxPlusEnabled = false
    AdminUser = "admin"
    AdminPass = ""
    SSLCertPath = ""
    SSLCert = ""
    SSLPort = 443
    SSLOpts = ""
    User = "www-data"
    WorkerProcesses = 2
    RLimitNoFile = 65535
    ProxyConnectTimeout = 600
    ProxySendTimeout = 600
    ProxyReadTimeout = 600
    SendTimeout = 600
    SSLCiphers = "HIGH:!aNULL:!MD5"
    SSLProtocols = "SSLv3 TLSv1 TLSv1.1 TLSv1.2"'

````

The only difference that I can see is that I am having to define a default network as there is a conflict on the default IP range between my private network and the default 10.0.0.x range docker sets.

```

docker network create --driver overlay --subnet=14.0.0.0/24 production_hwd

```


Any ideas what is wrong?

**Comment by ehazlett** [comment]
What is your host OS?  This looks correct. I'm going to try to re-create.

**Comment by robbydooo** [comment]
I am using centos 7

**Comment by ehazlett** [comment]
Thanks, what kernel version?  The reason I ask is I think there is an issue with overlapping subnets on older kernels.

**Comment by ehazlett** [comment]
This could be an issue with the different default overlay.  I will debug that as well.

**Comment by robbydooo** [comment]
Linux docker-ucp 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by robbydooo** [comment]
The Overly being the issue here would make a lot of sense. If that is the case is there a work around somehow? Is it that its expecting the IP address range to be 10.0.0.0/24 or that the name of the network needs to be something specific?

**Comment by robbydooo** [comment]
Is there anything I can do to help get this fixed? I have tried several different ways of setting this up but still no luck.

**Comment by ehazlett** [comment]
@robbydooo i'm standing up an env to try and re-produce.  any chance you could jump on IRC?

**Comment by robbydooo** [comment]
@ehazlett sure which irc? Can skype, slack chat also whatever is easier.

**Comment by ehazlett** [comment]
OK I have identified the issue.  Interlock does not yet support internal overlay networking (although it's on the roadmap).  In the short term you can work around this by using `ports` in your compose file.  For example,

```
...
services:                                                                       
    webapp:                                                                     
        image: "nginx"                                                          
        ports:                                                                  
            - "80"                                                              
        expose:                                                                 
            - "80"                                                              
        labels:                                                                 
            - "interlock.hostname=foo"                                          
            - "interlock.domain=local"
```

This will cause Swarm to expose the node IP and port configured for the container and Interlock will work.  I know this isn't ideal with overlay networking and I'm working to add that.  We need to add the ability to either specify via flags or detect internally whether overlay is active.  Also we need to be able to detect whether the user wants to use overlay or not.  These are the technical questions as to why it's not yet supported.

Hopefully this at least gets you working and I would love to have your feedback on future overlay support.
