### ISSUE TITLE
Feature request: Add support for context roots under a hostname

### ISSUE THREAD

**Issue by mbentley** [ehazlett/interlock#94]
In one use case that I am looking at, supporting context roots underneath a hostname would be an ideal solution.  Looking at the templates, it looks like much of the code use for websockets could be reused to make context roots work.  I'd expect that it would work something like:

```
labels:
  interlock.contextroot: "contextA"
  interlock.hostname: "app"
  interlock.domain: "example.com"
```

http://app.example.com/contextA

It would then allow multiple containers to serve up content under a single hostname where different containers may serve different portions of a collective service.

Thoughts on that?
